import numpy as np
import matplotlib.pyplot as plt
x1,z1,u1,t1,=np.loadtxt('../data/output1.dat',unpack=True)
x=np.reshape(x1,(15,26),order='F')
z=np.reshape(z1,(15,26),order='F')
u=np.reshape(u1,(15,26),order='F')
t=np.reshape(t1,(15,26),order='F')
plt.contourf(x/1000,z/1000,u,cmap='Spectral')
plt.colorbar()
plt.xlabel('Distance (km)')
plt.ylabel('Height (km)')
#plt.ylim(0.,6.0)
plt.title('Wind speed - 100 sec')
#plt.savefig('../plots/test1.png',dpi=600)
plt.show()
plt.contourf(x/1000,z/1000,t,cmap='Spectral')
plt.colorbar()
plt.xlabel('Distance (km)')
plt.ylabel('Height (km)')
plt.title('Potential temperature - 60 sec')
#plt.savefig('../plots/test1.png',dpi=600)
plt.show()
#plt.quiver(u1,v1,scale_units='inches',scale=20)
#plt.show()
