import numpy as np
import matplotlib.pyplot as plt
x1,z1,u1=np.loadtxt('../data/cross_section_mw1.dat',unpack=True)
x=np.reshape(x1,(15,26),order='F')
z=np.reshape(z1,(15,26),order='F')
u=np.reshape(u1,(15,26),order='F')
plt.contourf(x,z,u,cmap='Spectral')
plt.colorbar()
plt.xlabel('Distance (km)')
plt.ylabel('Height (km)')
#plt.ylim(0.,6.0)
plt.title('Wind speed - fc+0h')
plt.savefig('../plots/Fig_CS_mw1.png',dpi=600)
plt.show()
#plt.quiver(u1,v1,scale_units='inches',scale=20)
#plt.show()
