import numpy as np
import matplotlib.pyplot as plt
q12,q13,q14=np.loadtxt('../data/windsurf.dat',unpack=True)
q12a=np.reshape(q12,(26,26),order='F')
q13a=np.reshape(q13,(26,26),order='F')
q14a=np.reshape(q14,(26,26),order='F')
plt.contourf(q12a*1000.0,cmap='Spectral')
plt.colorbar()
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('Specific humidity level 12 - fc+30h')
plt.savefig('../plots/Fig_q12_fc30.png',dpi=600)
plt.show()
plt.contourf(q13a*1000,cmap='RdYlGn')
plt.colorbar()
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('Specific humidity level 13 - fc+30h')
plt.savefig('../plots/Fig_q13_fc30.png',dpi=600)
plt.show()
plt.contourf(q14a*1000,cmap='coolwarm')
plt.colorbar()
plt.xlabel('X axis')
plt.ylabel('Y axis')
plt.title('Specific humidity level 14 - fc+30h')
plt.savefig('../plots/Fig_q14_fc30.png',dpi=600)
plt.show()
